# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Maven_Build
  displayName: Maven Build
  jobs:
    - job: Build_Maven
      displayName: Build Maven
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
          
- stage: Copy Artifact
  displayName: Copy Artifact
  jobs:
    - job: Copy_Artifact
      displayName: Copy Artifact
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/'
          Contents: '*.jar'
          TargetFolder: '$(Build.SourcesDirectory)/Docker/'

- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Docker/Dockerfile'
        tags: |
          $(tag)