# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: BuildPack
  displayName: Build and Pack
  jobs:
    - job: BuildPack
      displayName: Build Pack
      pool:
        vmImage: 'ubuntu-latest'
      steps:
      - task: Maven@3
        inputs:
          mavenPomFile: 'pom.xml'
          publishJUnitResults: true
          testResultsFiles: '**/surefire-reports/TEST-*.xml'
          javaHomeOption: 'JDKVersion'
          mavenVersionOption: 'Default'
          mavenAuthenticateFeed: false
          effectivePomSkip: false
          sonarQubeRunAnalysis: false
          
      - task: CopyFiles@2
        inputs:
          SourceFolder: '$(Build.SourcesDirectory)/'
          Contents: '*.jar'
          TargetFolder: '$(Build.SourcesDirectory)/Docker/'
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            ls ./Docker/
            ls ./
            cp ./*.jar ./Docker/          
      - task: Docker@2
        displayName: Build an image
        inputs:
          command: build
          dockerfile: '$(Build.SourcesDirectory)/Docker/Dockerfile'
          tags: |
            $(tag)

        
